export const s = {
  container: { maxWidth: 600, margin: "0 auto", padding: "0 16px 100px", fontFamily: "'PingFang SC', 'Helvetica Neue', sans-serif", background: "#f8f8f6", minHeight: "100vh" },
  header: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "14px 0", borderBottom: "1px solid #eee", position: "sticky", top: 0, background: "#f8f8f6", zIndex: 10 },
  logo: { fontSize: 22, fontWeight: 700, color: "#f97316", letterSpacing: 0 },
  headerRight: { display: "flex", alignItems: "center", gap: 8 },
  userLabel: { fontSize: 13, color: "#555", cursor: "pointer", display: "flex", alignItems: "center" },
  nav: { display: "flex", gap: 8, padding: "12px 0" },
  navBtn: { flex: 1, padding: "8px 0", border: "1px solid #e5e7eb", borderRadius: 8, background: "#fff", cursor: "pointer", fontSize: 14, color: "#555" },
  navBtnActive: { background: "#f97316", color: "#fff", border: "1px solid #f97316", fontWeight: 600 },
  quotaBar: { display: "flex", alignItems: "center", justifyContent: "space-between", background: "#fff", borderRadius: 10, padding: "10px 14px", marginBottom: 8, fontSize: 13, color: "#666", boxShadow: "0 1px 3px rgba(0,0,0,0.04)" },
  quotaDots: { display: "flex", gap: 6 },
  quotaDot: { width: 10, height: 10, borderRadius: "50%", transition: "background 0.2s" },
  inviteBanner: { background: "#fff7ed", border: "1px solid #fed7aa", borderRadius: 10, padding: "10px 14px", marginBottom: 8, fontSize: 13, color: "#92400e" },
  loginBox: { textAlign: "center", padding: "80px 20px", position: "relative" },
  setupBox: { textAlign: "center", padding: "60px 20px" },
  loginEmoji: { fontSize: 48, marginBottom: 16 },
  loginTitle: { fontSize: 26, fontWeight: 800, marginBottom: 8, color: "#111" },
  loginSub: { color: "#888", marginBottom: 24, fontSize: 15 },
  card: { background: "#fff", borderRadius: 14, padding: 16, marginBottom: 10, boxShadow: "0 1px 4px rgba(0,0,0,0.05)" },
  cardTitle: { fontWeight: 700, marginBottom: 12, fontSize: 15, display: "flex", justifyContent: "space-between", alignItems: "center" },
  postTypeToggle: { display: "flex", gap: 4 },
  typeBtn: { padding: "4px 10px", borderRadius: 6, border: "1px solid #e5e7eb", background: "#fff", cursor: "pointer", fontSize: 12, color: "#666" },
  typeBtnActive: { background: "#f97316", color: "#fff", border: "1px solid #f97316" },
  fieldLabel: { fontSize: 12, color: "#999", marginBottom: 6, marginTop: 10 },
  tagRow: { display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 10 },
  tag: { padding: "5px 12px", borderRadius: 20, border: "1px solid #e5e7eb", background: "#fff", cursor: "pointer", fontSize: 13, color: "#444" },
  tagActive: { background: "#f97316", color: "#fff", border: "1px solid #f97316" },
  tagBadge: { padding: "3px 10px", borderRadius: 20, background: "#fff7ed", color: "#f97316", fontSize: 12, border: "1px solid #fed7aa" },
  topicBadge: { padding: "3px 10px", borderRadius: 20, background: "#eff6ff", color: "#3b82f6", fontSize: 12, border: "1px solid #bfdbfe", cursor: "pointer" },
  visibilityBadge: { fontSize: 11, padding: "1px 6px" },
  textarea: { width: "100%", padding: "10px 12px", borderRadius: 8, border: "1px solid #e5e7eb", fontSize: 14, marginBottom: 4, boxSizing: "border-box", outline: "none", resize: "none", fontFamily: "inherit", lineHeight: 1.6 },
  charCount: { fontSize: 11, color: "#bbb", textAlign: "right", marginBottom: 10 },
  input: { width: "100%", padding: "10px 12px", borderRadius: 8, border: "1px solid #e5e7eb", fontSize: 14, marginBottom: 10, boxSizing: "border-box", outline: "none" },
  btnPrimary: { padding: "10px 20px", background: "#f97316", color: "#fff", border: "none", borderRadius: 8, cursor: "pointer", fontWeight: 600, fontSize: 14, width: "100%", marginTop: 4 },
  btnOrange: { padding: "8px 16px", background: "#f97316", color: "#fff", border: "none", borderRadius: 8, cursor: "pointer", fontWeight: 600, fontSize: 14, whiteSpace: "nowrap" },
  btnSmall: { padding: "5px 12px", background: "#f3f4f6", border: "none", borderRadius: 6, cursor: "pointer", fontSize: 13, color: "#444" },
  upgradeBtn: { padding: "4px 10px", background: "#fff7ed", color: "#f97316", border: "1px solid #fed7aa", borderRadius: 6, cursor: "pointer", fontSize: 12 },
  unreadBadge: { background: "#f97316", color: "#fff", borderRadius: "50%", width: 20, height: 20, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 11, fontWeight: 700 },
  sectionTitle: { fontSize: 14, fontWeight: 700, color: "#333", margin: "8px 0 10px" },
  empty: { textAlign: "center", color: "#bbb", padding: 40, fontSize: 14 },
  emptyMatch: { textAlign: "center", color: "#bbb", padding: 40, fontSize: 14, lineHeight: 1.6 },
  postHeader: { display: "flex", alignItems: "center", gap: 10, marginBottom: 10 },
  avatarPlaceholder: { width: 38, height: 38, borderRadius: "50%", background: "#f97316", color: "#fff", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 700, fontSize: 16, flexShrink: 0, cursor: "pointer", overflow: "hidden" },
  avatarImg: { width: "100%", height: "100%", objectFit: "cover" },
  username: { fontWeight: 600, fontSize: 14, cursor: "pointer" },
  timeText: { fontSize: 12, color: "#aaa", display: "flex", alignItems: "center", gap: 6 },
  matchBadge: { fontSize: 11, padding: "1px 7px", borderRadius: 10, background: "#fff7ed", color: "#f97316", border: "1px solid #fed7aa" },
  normalBadge: { fontSize: 11, padding: "1px 7px", borderRadius: 10, background: "#f3f4f6", color: "#888", border: "1px solid #e5e7eb" },
  matchScore: { fontSize: 12, color: "#f97316", fontWeight: 600 },
  postContent: { fontSize: 14, color: "#333", marginBottom: 10, lineHeight: 1.7 },
  noteText: { fontSize: 13, color: "#555", marginBottom: 10, lineHeight: 1.6 },
  mention: { color: "#3b82f6", fontWeight: 600 },
  hashtag: { color: "#f97316", fontWeight: 600, cursor: "pointer" },
  actionRow: { display: "flex", gap: 20, marginTop: 6 },
  actionBtn: { background: "none", border: "none", cursor: "pointer", fontSize: 13, color: "#888", padding: 0 },
  commentSection: { marginTop: 12, borderTop: "1px solid #f5f5f5", paddingTop: 10 },
  commentItem: { fontSize: 13, color: "#555", marginBottom: 6 },
  commentInputRow: { display: "flex", gap: 8, marginTop: 8 },
  chatBox: { display: "flex", flexDirection: "column", height: "calc(100vh - 160px)" },
  chatHeader: { padding: "12px 0", borderBottom: "1px solid #eee", display: "flex", justifyContent: "space-between", alignItems: "center" },
  messageList: { flex: 1, overflowY: "auto", padding: "12px 0", display: "flex", flexDirection: "column", gap: 8 },
  messageBubble: { maxWidth: "72%", padding: "8px 14px", borderRadius: 16, fontSize: 14, lineHeight: 1.5 },
  chatInputRow: { display: "flex", gap: 8, paddingTop: 10, borderTop: "1px solid #eee" },
  profileCard: { background: "#fff", borderRadius: 14, padding: 24, textAlign: "center", marginBottom: 12, boxShadow: "0 1px 4px rgba(0,0,0,0.05)" },
  profileAvatar: { width: 72, height: 72, borderRadius: "50%", background: "#f97316", color: "#fff", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 28, fontWeight: 700, margin: "0 auto 12px" },
  profileName: { fontSize: 20, fontWeight: 700, marginBottom: 4 },
  profileSub: { fontSize: 13, color: "#aaa" },
  overlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.4)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 100 },
  modal: { background: "#fff", borderRadius: 16, padding: 24, width: "85%", maxWidth: 360, boxShadow: "0 8px 32px rgba(0,0,0,0.15)" },
  modalTitle: { fontSize: 17, fontWeight: 700, marginBottom: 8 },
  modalSub: { fontSize: 14, color: "#666", marginBottom: 16, lineHeight: 1.6 },
};
